### ISSUE TITLE
Field name simplification broken after renaming with Smart Tag 

### ISSUE THREAD

**Issue by gbogarinb** [graphile/pg-simplify-inflector#29]
I'm submitting a ... 

* [x] bug report
* [ ] feature request
* [ ] question 

PostGraphile version: ^4.5.5
pg-simplify-inflector version: ^5.0.0-beta.1

Hi, so this is a question regarding the naming of fields based on foreign keys once the foreign key column is renamed.
I have these two tables:
```sql
create table something(
        something_id integer not null primary key,
        name text
);
create table something_data(
        something_data_id integer not null primary key,
	something_id integer not null references something on delete cascade,
	data text
)
```
This creates the following schemas:
```graphql
  something(somethingId: 10) {
    somethingId
    somethingDataConnection {
      totalCount
    }
  }
  somethingDatum(somethingDataId: 10) {
    data
    something {
      somethingId
    }
  }
```
, where **somethingDataConnection** and **something** are fields based on the foreign key on the column something_data.something_id.
But let's say I want to rename something.something_id to just something.some_id.
```sql
comment on column something.something_id is E'@name some_id';
```
This only changes that field:
```graphql
  something(someId: 10) {
    someId
    somethingDataConnection {
      totalCount
    }
  }
  somethingDatum(somethingDataId: 10) {
    data
    something {
      someId
    }
  }
```
But now for consistency I also want to rename something_data.something_id:
```sql
comment on column something_data.something_id is E'@name some_id';
```
and this is the result:
```graphql
  something(someId: 10) {
    someId
    somethingDataBySomeIdConnection {
      totalCount
    }
  }
  somethingDatum(somethingDataId: 10) {
    data
    somethingBySomeId {
      someId
    }
  }
```
So it seems that after renaming the foreign key column pg-simplify-inflector does not recognize it as such anymore, I think I can fix the first schema by doing:
```sql
comment on constraint something_data_something_id_fkey on something_data is E'@foreignFieldName somethingData';
```
But the second one (somethingBySomeId) would still be broken and I would prefer a way to fix this from the root since renaming is a thing I do a lot because the database has a differente naming convention than the client api.

Current behavior: After renaming foreing key column the suffix By[Field]Id is added again.

Expected behavior: The suffix should not be added.

**Comment by benjie** [comment]
I've moved this issue to the simplify inflectors plugin repo, since I believe that's really what you're asking about.

**Comment by benjie** [comment]
We currently use the resulting column name rather than the original column name for this:

https://github.com/graphile/pg-simplify-inflector/blob/38a008a7db3d2a421d57ee6d6cc8291de1222d6f/index.js#L135-L142

I'd expect it to work from a scan over the code, I wonder if there's something else going on? Failing that, I'd need to step through the inflector code line by line in this:

https://github.com/graphile/pg-simplify-inflector/blob/38a008a7db3d2a421d57ee6d6cc8291de1222d6f/index.js#L183-L200

Namely: I'd expect `baseName` to equal `some` and thus for it to work, but judging by what you're saying that's not the case.

**Comment by gbogarinb** [comment]
I tried to replicate this on a new database and got a slightly different result, the first time I actually executed this
```sql
comment on column something_data.something_id is E'@name some_id;';
```
with a semicolon at the end of the comment, what's strange is that it does change the field to some_id (doesn't complain about the semicolon), but it doesn't work with the foreign key field for some reason, after executing it without the semicolon I do get the result that you suggested but only in the second schema:
```graphql
  somethingDatum(somethingDataId: 10) {
    someId
    some {
      name
    }
  }
```
The first schema still remains with somethingDataBySomeIdConnection.

**Comment by benjie** [comment]
Maybe there's something else in there - invisible whitespace or something - that's tricking it?

**Comment by gbogarinb** [comment]
The problem seems to be here:
https://github.com/graphile/pg-simplify-inflector/blob/38a008a7db3d2a421d57ee6d6cc8291de1222d6f/index.js#L250-L275

Here is a log before and after the comment.

```
Before
getBaseNameFromKeys something
_foreignTable.name something
baseNameMatches singularizedName something
baseNameMatches result true
_manyRelationByKeysBase somethingData
manyRelationByKeys somethingDataConnection

After
getBaseNameFromKeys some
_foreignTable.name something
baseNameMatches singularizedName something
baseNameMatches result false
_manyRelationByKeysBase null
manyRelationByKeys somethingDataBySomeIdConnection
```
_manyRelationByKeysBase is returning null since now baseName and singularizedName (computed from _foreignTable.name) aren't the same anymore thus making manyRelationByKeys ending up using oldInflection.manyRelationByKeys.

**Comment by gbogarinb** [comment]
My current solution is to change this:
https://github.com/graphile/pg-simplify-inflector/blob/38a008a7db3d2a421d57ee6d6cc8291de1222d6f/index.js#L191
https://github.com/graphile/pg-simplify-inflector/blob/38a008a7db3d2a421d57ee6d6cc8291de1222d6f/index.js#L221
https://github.com/graphile/pg-simplify-inflector/blob/38a008a7db3d2a421d57ee6d6cc8291de1222d6f/index.js#L242
by this:
```javascript
if (detailedKeys[0].tags.name || this.baseNameMatches(baseName, [table or _foreignTable].name)) {
```
The reasoning being that if there is a name tag then baseNameMatches will always return false, I didn't find any side effect so far but I'm not sure if this reasoning makes sense because I didn't have enough time to actually understand what that method was supposed to do.

**Edit**: I did find some side effects, but I'm not entirely sure if they're actually harmful.
```slq
create table person(
person_id integer not null primary key generated by default as identity);

create table person_cart(
person_id integer not null primary key references person on delete cascade);

create table person_address(
person_id integer not null references person on delete cascade);
```
Instead of generating this:
```graphql
person(personId: 10) {
    personAddressesConnection {
      totalCount
    }
    personCartByPersonId {
      personId
    }
  }
```
it generates this:
```graphql
person(personId: 10) {
    personAddressesConnection {
      totalCount
    }
    personCart {
      personId
    }
  }
```
Of course only if person_cart has a smart tag.
```json
person_cart: {
	attribute: {
		person_id: {
			tags: {
				name: "person_id"
			}
		}
	}
},
```

**Comment by benjie** [comment]
This is working as designed. Ignoring smart comments the issue is basically this:

```sql
create table something(
  some_id integer not null primary key,
  name text
);
create table something_data(
  something_data_id integer not null primary key,
  some_id integer not null references something on delete cascade,
  data text
);
```

Since the table/type name for `something` is `something` (and not `some`), the `some_id` reference is inferred to have a special meaning rather than a simple relationship. It's hard to explain with this nonsense schema, so let's come up with a more reasonable one:

```sql
create table people (
  id serial primary key,
  name text
);

create table books (
  id serial primary key,
  title text,
  author_id int not null references people,
  publisher_id int not null references people
);
```

In this table we generate `type Book { author: Person }` as expected. Also `type Book { publisher: Person }`. Now we can't add a field on `People` called `books` because it effectively points to two different places - once for author and once for publisher, so instead you'd get `booksByAuthorId: [Book]` and `booksByPublisherId: [Book]`*. Now imagine if our books table was:

```sql
create table books (
  id serial primary key,
  title text,
  author_id int not null references people
);
```

Here we only have one reference to `people`, so we _could_ add `type Person { books: [Book] }` but if we were to do so and then later add the `publisher_id` field, we'd introduce a breaking schema change, and all our GraphQL queries would become invalid. For this reason we _only_ use the simplified `books` name if the relationship is itself simple (i.e. in this case if the books.author_id column was instead called `books.person_id`).

I hope this clarifies why your request cannot be granted in general, and why you need to add custom naming because your problem doesn't generalise to all databases.



* Actually, we have workarounds for this called `getOppositeBaseName` (which you can extend) which notes if it's `author_id` then the reverse can be called `authoredBooks` rather than `bookByAuthorId`, but this isn't something we can do in general because we don't have a list of all the possible relationships.
